/**
 * Re-exports GraphQL schema input/filter types for REST datasource methods.
 * Generated by graphql-codegen from src/schema/ — run `pnpm codegen`.
 */
import type { QueryTasksArgs, TaskFilterInput } from '../generated/graphql';

export type {
  CalculateTravelTimeInput,
  ConnectCalendarInput,
  ConnectIntegrationInput,
  CreateApiKeyInput,
  CreateBookingInput,
  CreateCalendarEventInput,
  CreateFocusTimeBlockInput,
  CreateGoalInput,
  CreateKanbanBoardInput,
  CreateNoMeetingDayInput,
  CreatePlanInput,
  CreatePlanTemplateInput,
  CreateProjectInput,
  CreateSchedulingLinkInput,
  CreateSmart1on1Input,
  CreateSubtaskInput,
  CreateTaskDependencyInput,
  CreateTaskInput,
  CreateTeamInput,
  CreateWebhookInput,
  GeneratePlanInput,
  InviteTeamMemberInput,
  MoveTaskInKanbanInput,
  PlanFilterInput,
  QueryGoalsArgs,
  QueryPlanTemplatesArgs,
  QueryPlansArgs,
  QueryProjectsArgs,
  QueryTasksArgs,
  SyncUserInput,
  Task,
  TaskFilterInput,
  TaskInfo,
  UpdateCalendarDefenseInput,
  UpdateCalendarEventInput,
  UpdateFocusTimeBlockInput,
  UpdateGoalInput,
  UpdateIntegrationInput,
  UpdateKanbanBoardInput,
  UpdateNotificationPreferencesInput,
  UpdateOnboardingProgressInput,
  UpdatePlanInput,
  UpdatePriorityHoursInput,
  UpdateProjectInput,
  UpdateSchedulingLinkInput,
  UpdateSmart1on1Input,
  UpdateTaskInput,
  UpdateTeamInput,
  UpdateUserProfileInput,
  UpdateUserSettingsInput,
  UpdateWebhookInput,
  WorkHoursInput,
} from '../generated/graphql';

export interface GoogleCalendarDateTime {
  date?: string;
  dateTime?: string;
}

/** Raw event shape returned by the REST calendar API (Google Calendar format). */
export interface GoogleCalendarApiEvent {
  id: string;
  summary?: string;
  title?: string;
  description?: string;
  start?: GoogleCalendarDateTime | string;
  end?: GoogleCalendarDateTime | string;
  location?: string;
  attendees?: Array<string | RestCalendarEventAttendee>;
}

/** Combined filter fields accepted by getTasks from nested or flat GraphQL args. */
export type TaskQueryFilterSource = TaskFilterInput &
  Pick<QueryTasksArgs, 'goalId' | 'projectId' | 'isCompleted' | 'scheduledDate'>;

export type RestListParams = Record<string, string | number | boolean | string[] | undefined>;

export interface RestCalendarEventAttendee {
  email?: string;
}

export interface RestCalendarEvent {
  id: string;
  title: string;
  description?: string;
  start: string;
  end: string;
  allDay?: boolean;
  attendees?: Array<string | RestCalendarEventAttendee>;
}

export interface RestTaskDependencySummary {
  id: string;
  title: string;
  isCompleted: boolean;
}
